using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using RTMPE.SDK.Conversion.Core;

namespace RTMPE.SDK.Analyzers
{
    /// <summary>
    /// Surfaces the Phase-5 authority classification as an informational
    /// diagnostic: one RTMPE9001 per concrete component type, carrying the role
    /// the deterministic rubric assigns and the signals that produced it.
    /// Advisory only — this analyzer suggests nothing it would rewrite, and the
    /// same <see cref="AuthorityClassifier"/> also feeds the readiness report's
    /// authority block, so the IDE and the CI artifact can never disagree.
    /// </summary>
    [DiagnosticAnalyzer(LanguageNames.CSharp)]
    public sealed class AuthorityInfoAnalyzer : DiagnosticAnalyzer
    {
        private static readonly DiagnosticDescriptor Classification = new DiagnosticDescriptor(
            id: DiagnosticIds.AuthorityClassification,
            title: "Type authority classification (advisory)",
            messageFormat: "'{0}' authority classification: {1} — {2}",
            category: "RTMPE.Authority",
            defaultSeverity: DiagnosticSeverity.Info,
            isEnabledByDefault: true,
            description: "The deterministic Phase-5 rubric classifies each component type's "
                + "authority posture from its own static signals (base type, NetworkVariable "
                + "state, owner guards, RPC surface, lifecycle overrides, scene-object wiring). "
                + "The verdict is advisory: it changes no source, transfers no ownership, and "
                + "promises no enforcement the client-authoritative-with-relay runtime does not "
                + "perform.",
            helpLinkUri: DiagnosticHelp.LinkFor(DiagnosticIds.AuthorityClassification));

        public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics
            => ImmutableArray.Create(Classification);

        public override void Initialize(AnalysisContext context)
        {
            context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
            context.EnableConcurrentExecution();
            context.RegisterCompilationStartAction(OnCompilationStart);
        }

        private static void OnCompilationStart(CompilationStartAnalysisContext context)
        {
            var sdk = AuthoritySdkSymbols.Resolve(context.Compilation);
            if (!sdk.HasUnitySurface)
            {
                return;
            }

            // One model cache for the whole compilation, shared across the symbol
            // actions the host runs concurrently: types declared in one file bind
            // that file's model once between them, rather than once apiece. The role
            // itself is a pure function of a type's intrinsic signals, so nothing
            // else crosses type boundaries.
            var models = new SemanticModelCache(context.Compilation);
            context.RegisterSymbolAction(c => ClassifyType(c, sdk, models), SymbolKind.NamedType);
        }

        private static void ClassifyType(
            SymbolAnalysisContext context, AuthoritySdkSymbols sdk, SemanticModelCache models)
        {
            var type = (INamedTypeSymbol)context.Symbol;
            if (!sdk.IsProjectNode(type))
            {
                return;
            }

            var signals = AuthoritySignalExtractor.Extract(type, models, sdk);
            var verdict = AuthorityClassifier.Classify(signals);

            var location = PreferredLocation(type);
            if (location is null)
            {
                return;
            }

            context.ReportDiagnostic(Diagnostic.Create(
                Classification,
                location,
                type.Name,
                verdict.Role,
                string.Join("; ", verdict.Evidence)));
        }

        // A partial type may declare its first part in a generated file; a
        // diagnostic placed there is filtered by the generated-code opt-out and
        // the classification would silently vanish. Prefer a hand-written part,
        // detecting "generated" the way Roslyn's own suppression does — by
        // filename convention AND the leading <auto-generated> header comment.
        private static Location PreferredLocation(INamedTypeSymbol type)
        {
            Location fallback = null;
            foreach (var location in type.Locations)
            {
                if (!location.IsInSource)
                {
                    continue;
                }

                fallback ??= location;
                if (!IsGeneratedTree(location.SourceTree))
                {
                    return location;
                }
            }

            return fallback;
        }

        private static bool IsGeneratedTree(SyntaxTree tree)
            => LooksGeneratedByName(tree.FilePath) || HasAutoGeneratedHeader(tree);

        private static bool LooksGeneratedByName(string filePath)
            => filePath is not null
                && (filePath.EndsWith(".g.cs", System.StringComparison.OrdinalIgnoreCase)
                    || filePath.EndsWith(".g.i.cs", System.StringComparison.OrdinalIgnoreCase)
                    || filePath.EndsWith(".generated.cs", System.StringComparison.OrdinalIgnoreCase)
                    || filePath.EndsWith(".designer.cs", System.StringComparison.OrdinalIgnoreCase));

        // The Roslyn/T4/Unity convention: a leading `// <auto-generated`
        // (or `/* <auto-generated`) comment in the file's first trivia marks the
        // whole file generated, which the generated-code opt-out then suppresses.
        private static bool HasAutoGeneratedHeader(SyntaxTree tree)
        {
            var firstToken = tree.GetRoot().GetFirstToken(includeZeroWidth: true);
            foreach (var trivia in firstToken.LeadingTrivia)
            {
                if (trivia.IsKind(SyntaxKind.SingleLineCommentTrivia)
                    || trivia.IsKind(SyntaxKind.MultiLineCommentTrivia))
                {
                    string text = trivia.ToString();
                    if (text.IndexOf("<auto-generated", System.StringComparison.OrdinalIgnoreCase) >= 0)
                    {
                        return true;
                    }
                }
            }

            return false;
        }
    }
}
