// RTMPE SDK — Runtime/Core/NetworkPrefabRegistry.cs
//
// The asset that carries the Editor's prefab ledger into the player.
//
// The ledger itself lives in the Editor and knows GUIDs; a build does not have
// one, and a GUID resolves to nothing at runtime. Until this asset existed the
// crossing was made by hand — a RegisterPrefab call per prefab, written by the
// integrator, in a place they had to remember to reach before spawning — and a
// missed call is a spawn that fails on every client but the one that made it.
//
// ⚠️ Every prefab named here is a HARD reference, so every one of them enters
// every build whether or not the game ever spawns it. That is the same trade
// Unity's own NetworkPrefabsList makes, and it is stated here and in the
// documentation rather than left to be discovered in a build report.

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using UnityEngine;

namespace RTMPE.Core
{
    /// <summary>
    /// A table of prefab ids and prefabs that the SDK loads into the spawn manager
    /// when a session is built. Assign it to
    /// <see cref="NetworkSettings.prefabRegistry"/>.
    /// </summary>
    /// <remarks>
    /// <para><b>Window → RTMPE → Network Prefabs</b> generates it, together with
    /// the <c>RtmpePrefabIds</c> constants, and allocates the ids. Each generation
    /// replaces every row, so edits made by hand do not last.
    /// <b>Create → RTMPE → Prefab Registry</b> creates an empty one.</para>
    /// <para>A row without a prefab is skipped, and when two rows share an id
    /// the later row's prefab is used; both are reported in the Console. Every
    /// prefab in the table is included in the build.</para>
    /// </remarks>
    [CreateAssetMenu(
        fileName = "RtmpePrefabRegistry",
        menuName = "RTMPE/Prefab Registry",
        order    = 2)]
    public sealed class NetworkPrefabRegistry : ScriptableObject, ISerializationCallbackReceiver
    {
        [SerializeField]
        [Tooltip("Prefab id → prefab, generated by Window → RTMPE → Network Prefabs. " +
                 "Every prefab listed here is included in the build.")]
        private List<NetworkPrefabEntry> entries = new List<NetworkPrefabEntry>();

        /// <summary>
        /// The rows, in order; read-only. Never <see langword="null"/>, though a
        /// row can be.
        /// </summary>
        public IReadOnlyList<NetworkPrefabEntry> Entries
            => _readOnly ?? (_readOnly = new ReadOnlyCollection<NetworkPrefabEntry>(
                   entries ?? (entries = new List<NetworkPrefabEntry>())));

        [NonSerialized]
        private ReadOnlyCollection<NetworkPrefabEntry> _readOnly;

        /// <summary>
        /// Replace every row. The generator's entry point — the Editor
        /// assembly reaches it through <c>InternalsVisibleTo</c> rather than
        /// through a serialised-property edit, so the shape written is the
        /// shape this type declares and not a hand-built copy of it.
        /// </summary>
        internal void SetEntries(List<NetworkPrefabEntry> replacement)
        {
            entries   = replacement ?? new List<NetworkPrefabEntry>();
            // The wrapper wraps the list that was there; a replacement leaves it
            // describing rows this registry no longer holds.
            _readOnly = null;
        }

        void ISerializationCallbackReceiver.OnBeforeSerialize()
        {
        }

        /// <remarks>
        /// 🔑 <see cref="SetEntries"/> is not the only writer of the field it
        /// clears. Unity assigns a fresh list into a serialised field whenever
        /// it deserialises the object — a re-import, an undo, a revert — and
        /// none of those goes through this type at all, so the wrapper was left
        /// describing rows the asset no longer holds and every reader that took
        /// <see cref="Entries"/> afterwards got the old ones.
        /// <para>
        /// ⚠️ A field assignment and nothing else: this runs on a loading thread,
        /// where the Unity API is not available.
        /// </para>
        /// </remarks>
        void ISerializationCallbackReceiver.OnAfterDeserialize()
        {
            _readOnly = null;
        }
    }
}
